dist: trusty
sudo: required
language: python
python:
  - '3.6'
os:
  - linux
env:
  global:
    - APP_ID=15634
  matrix:
    - TEST_DIR=dawn
    - TEST_DIR=hibike/travis
    - TEST_DIR=runtime
    - TEST_DIR=shepherd
cache:
  pip: true
  directories:
    - node_modules
    - $HOME/.cache/yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_516b8f19f8a6_key -iv $encrypted_516b8f19f8a6_iv -in DevOps/pipeline/piecentral-artifacts.pem.encrypted -out DevOps/pipeline/piecentral-artifacts.pem -d
  - nvm install --lts
  - pip3 install pipenv
  - mkdir -p artifacts
  - if [[ $TEST_DIR = dawn ]] && git tag -l --points-at HEAD | grep dawn; then
    export DEPLOY_ARTIFACTS=1; fi
  - if [[ $TEST_DIR = runtime ]] && git tag -l --points-at HEAD | grep runtime; then
    export DEPLOY_ARTIFACTS=1; fi
  - if [[ $TEST_DIR = shepherd ]] && git tag -l --points-at HEAD | grep shepherd; then
    export DEPLOY_ARTIFACTS=1; fi
  - pushd $TEST_DIR
  - mkdir -p build-deps
  - export PATH="$PATH:$PWD/build-deps/bin"
  - popd
install:
  - pushd $TEST_DIR
  - make install
  - if [[ $DEPLOY_ARTIFACTS = 1 ]]; then make artifacts-install; fi
  - popd
script:
  - pushd $TEST_DIR
  - make test
  - make lint
  - if [[ $DEPLOY_ARTIFACTS = 1 ]]; then make artifacts; fi
  - popd
branches:
  only:
    - master
    - /^shepherd\/.*$/
    - /^dawn\/.*$/
    - /^devops\/.*$/
    - /^hibike\/.*$/
    - /^runtime\/.*$/
    - /^test\/.*$/
deploy:
  provider: script
  script: bash DevOps/pipeline/deploy-artifacts.sh "$APP_ID" "$TRAVIS_TAG" "$(pwd)/artifacts"
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $DEPLOY_ARTIFACTS = 1
notifications:
  slack:
    rooms:
      - secure: iByImumEaLfRhxD5wxER3qovftyqSeaQdtdp5y80MSPZMa9AL6NkpyhZPl8WaQxUYvvzWo4/dbal+Qb17ew4hRDsprKbvXh3SP/0SLSe0QAK3ShB+iLBAFX04ZoTRMxdgKvU4LZPbJGSizBWD6lHHz3JCILSpjXtfgL1g74vejVJY2VqMW4Vn4YXfPx39z5v23O9GNzx9S2zGb0dN77ilSRJr/wVzsYqZD8jcgaD63pZ/TCSgxJcVQAvztVaWKkbh19qrP6M4WV1rxIZN8ksnBe1gUJ/VIylMWnf3CRwLaJw4+Z+aqm1GUbD7tsi9BA2D7gmlJC/yv4vzejMCtOpU8z4ymBpvJ6A7uBdv5CMGcOWx35FEpB5LwSGKXk0/5/Ar3HjHzQtB/K7a7PuzvHUROdNUi+9Q6kUAZlEfzEsbEd/sxMy09m6kBKUpluDueJCBcS0qGYlZ+7roQwEs5CEPBqOUhZne3kNH+HXsyHgs4r83FlPEqqnhdswqQYgWYOdrIQVUXX3L8CnCpuFojevwdN+nb/ahwsl0XQl5lgaFcIsU4tZpYHxXExzpWJfN7Y3MvRbFOfNab8LSodAHjvvzXJrmh8lrlv3TYtW5mWDyPg56CTysMOuVRyc74bvvhidff3tUTw62VqH13XESVcdsOEv0g8Jz4ZnzInxJTimX9o=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "@onibrow Your meatballs are ready!"
    on_success: change
    on_failure: always
